<h3><b>Introduction to Data Analytics - Exercise set 1 - Python and NumPy Basics</b></h3>

Put all your exercises (Jupyter Notebooks or Python-files) in your course Git-project.
Use either code comments or Jupyter Notebook markdown (text) to document which exercise you are doing and what a certain code section does! 
You can return all of these exercises in a single Jupyter Notebook, if you wish.

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/numpylogo.png" width="250"/>

In [46]:
import numpy as np


In [47]:
# setup all needed modules and configurations
import numpy as np

# re-style the NumPy arrays
# remember to install needed module first:
# pip3 install numpy-html
%load_ext numpy_html

ModuleNotFoundError: No module named 'numpy_html'

Run the cell below to enable custom style for NumPy arrays:

In [ ]:
%%html
<style>
table {margin-top: 16pt;}
td {font-family: Arial, Helvetica, sans-serif !important; font-weight: 600; white-space: normal !important;}
tr:nth-child(even) {background: #b0d9eb !important; color: black}
tr:nth-child(odd) {background: #8fb1bf !important; color: black}
</style>

<h4><b>1. Create these lists without NumPy:</b></h4>

- List of 15 ones

- List of 15 number 7's

- List of numbers from 100 to 150

- List of even numbers between 0 and 100

- List of years that are divisible by 4 between 1950 and 2020

<br>

<b>Tip: creating a list with Python code is usually something like this:</b>

<pre>
numbers = []

for x in range(0, 5):
    numbers.append(x)
</pre>

<h3><i>Exercise 1.1</i></h3>

In [ ]:
data = []

for d in range(15):
    d = 1
    data.append(d)
data

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [ ]:
data = []

for d in range(15):
    d = 7
    data.append(d)
data

[7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7]

In [ ]:
data = []

for i in range(100,150):
    data.append(i)
data

[100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149]

In [ ]:
data = []

for i in range(0,100):
    if i % 2 == 0:
        data.append(i)
data

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98]

In [ ]:
data = []

for i in range(1950,2020):
    if i % 4 == 0:
        data.append(i)
data

[1952,
 1956,
 1960,
 1964,
 1968,
 1972,
 1976,
 1980,
 1984,
 1988,
 1992,
 1996,
 2000,
 2004,
 2008,
 2012,
 2016]

<h4><b>2.	Now, create these arrays with NumPy!</b></h4>

- Array of 15 zeroes

- Array of 15 ones

- Array of 15 number 7's

- Array of numbers from 100 to 150

- Array of numbers from 1900 to 2021

- Array of even numbers between 0 and 100

- Array of years that are divisible by 4 between 1950 and 2020



<h3><i>Exercise 1.2</i></h3>

In [ ]:
data = np.zeros(15).astype(int)
data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
data = np.ones(15).astype(int)
data


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
data = (np.ones(15)*7).astype(int)
data

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

#I think it's easier and faster to code using numpy compared to plain pyhton

In [ ]:
data = np.arange(100,150).astype(int)
data

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

In [ ]:
data = np.arange(100,150).astype(int)
data

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])

<h4><b style="color: red">Note: compare the NumPy code to the plain Python code after doing the exercises. Easier or more difficult? :) 
(answer in code comments or as text in Jupyter Notebook)</b></h4>

In [ ]:
data = np.arange(1900,2020).astype(int)
data

array([1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910,
       1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921,
       1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932,
       1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943,
       1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954,
       1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965,
       1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976,
       1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987,
       1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
       1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009,
       2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019])

In [ ]:
data = np.arange(0,100, 2).astype(int)
data

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [ ]:
data = np.arange(1900,2020, 4).astype(int)
data

array([1900, 1904, 1908, 1912, 1916, 1920, 1924, 1928, 1932, 1936, 1940,
       1944, 1948, 1952, 1956, 1960, 1964, 1968, 1972, 1976, 1980, 1984,
       1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016])

<h3><b>3. Let's try out NumPy matrices:</b></h3>

- Create a 7x7 matrix, with values from 1 to 49

    - Extra task: Create this matrix (list of lists) without NumPy in Python!

<br>

- Generate 8x8 random number matrix, values between 0 and 5

- Generate 8x8 random number matrix, using standard normal distribution values (= values are between -3 and 3)


<h3><b>Exercise 1.3</b></h3>


In [ ]:
data = np.arange(1,50).reshape(7,7)
data

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [ ]:
data = np.random.randint(0, 5, 64).reshape(8,8)
data

array([[0, 3, 0, 2, 0, 1, 1, 3],
       [1, 2, 1, 2, 3, 2, 3, 4],
       [3, 4, 3, 1, 0, 4, 0, 4],
       [2, 1, 1, 4, 1, 2, 0, 3],
       [3, 1, 0, 4, 4, 0, 3, 0],
       [2, 0, 2, 4, 0, 4, 3, 4],
       [2, 3, 4, 2, 2, 0, 0, 3],
       [4, 1, 0, 0, 4, 1, 1, 2]])

In [ ]:
# exercise 1.3, NumPy matrices
# use additional code cells or different variable names for each subtask


In [ ]:
data = np.random.randn(8,8)
data

array([[-0.27872718,  0.98517557, -0.29125734,  0.97289197, -1.10299266,
        -0.35861248, -0.20965634,  0.65346117],
       [ 1.28759379,  0.45846157, -1.27718889,  0.80043922, -0.78938799,
        -1.48197053, -0.03454314,  1.0778971 ],
       [-1.01465268,  1.5683861 , -1.12633198, -1.05899047,  0.40444731,
        -0.44606318, -0.50468752, -0.78318252],
       [-0.33435675,  0.96434564, -1.47006734, -0.70620866,  0.42199392,
        -0.56951512,  0.40519366,  0.88935929],
       [-1.87625832,  0.90203501,  0.87457381, -1.68009775, -0.59869486,
        -0.2491481 , -0.28444823, -0.9437826 ],
       [ 0.35190702, -0.28082981,  0.14369698,  0.91824669, -1.86951603,
        -0.6982678 ,  1.488016  ,  0.07559204],
       [-0.81627018,  0.56056947, -1.11462425, -0.20725661,  0.70502911,
         0.7445069 ,  0.40154135,  0.49277406],
       [-0.49093285,  1.47547493,  1.80358676,  1.08404334,  0.91634429,
        -0.52930749, -0.69481366,  0.84308472]])

<h3><b>4. Create a linearly spaced… </b></h3>

- array (list/vector) of 10 values between value 0 and 1

- 10x10 matrix between values 0 and 5

    - Extra task: create this matrix without NumPy as well!


<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/cubes.png"/>


<h3><b>Exercise 1.4</b></h3>

In [ ]:
# exercise 1.4, linspace
# use additional code cells or different variable names for each subtask
data = np.linspace(0, 1, 10)
data

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
data = np.linspace(0, 5, 100).reshape(10, 10)
data

array([[0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
        0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545],
       [0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
        0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596],
       [1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
        1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646],
       [1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
        1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697],
       [2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
        2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747],
       [2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
        2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798],
       [3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
        3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848],
       [3.53535354, 3.58585859, 3.6363636

<h3><b>5. Recreate the matrices in code based on the pictures.</b></h3>

- Create this 3x5 matrix with NumPy:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix1.png"/>


Note: The values above have no logic, you'll have to feed basic Python lists to NumPy for this result


<b><h3>Exercise 1.5</h3></b>

In [ ]:
# exercise 1.5a, create matrix
data = [23,34,54,31,75,33,56,78,65,97,41,32,11,39,51]
data = np.array(data).reshape(3, 5)
data


array([[23, 34, 54, 31, 75],
       [33, 56, 78, 65, 97],
       [41, 32, 11, 39, 51]])

- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix2.png" width="800"/>

In [ ]:
# exercise 1.5b, generate NumPy array / matrix
data = np.arange(128, 256).reshape(8, 16)
data


array([[128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143],
       [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
        157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172,
        173, 174, 175],
       [176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188,
        189, 190, 191],
       [192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204,
        205, 206, 207],
       [208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220,
        221, 222, 223],
       [224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236,
        237, 238, 239],
       [240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252,
        253, 254, 255]])

- Generate this NumPy array:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix3.png" width="500"/>

<b>Tips:</b> arange-function (and step-parameter) + reshape is recommended. Alternatively you can use broadcasting and division if you like.

In [ ]:
# exercise 1.5c, generate NumPy array / matrix
data = np.linspace(0.05,5, 100).reshape(10, 10)
data


array([[0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ],
       [0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  ],
       [1.05, 1.1 , 1.15, 1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 ],
       [1.55, 1.6 , 1.65, 1.7 , 1.75, 1.8 , 1.85, 1.9 , 1.95, 2.  ],
       [2.05, 2.1 , 2.15, 2.2 , 2.25, 2.3 , 2.35, 2.4 , 2.45, 2.5 ],
       [2.55, 2.6 , 2.65, 2.7 , 2.75, 2.8 , 2.85, 2.9 , 2.95, 3.  ],
       [3.05, 3.1 , 3.15, 3.2 , 3.25, 3.3 , 3.35, 3.4 , 3.45, 3.5 ],
       [3.55, 3.6 , 3.65, 3.7 , 3.75, 3.8 , 3.85, 3.9 , 3.95, 4.  ],
       [4.05, 4.1 , 4.15, 4.2 , 4.25, 4.3 , 4.35, 4.4 , 4.45, 4.5 ],
       [4.55, 4.6 , 4.65, 4.7 , 4.75, 4.8 , 4.85, 4.9 , 4.95, 5.  ]])

<h3><b>6. Use this matrix in your code:</b></h3>

dataset = np.arange(1, 37).reshape(6, 6)

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix4.png"/>


<b><h3>Exercise 1.6</h3></b>

In [ ]:
# exercise 1.6a, matrix slicing
dataset = np.arange(1, 37).reshape(6, 6)
dataset

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

- Create a slice of the matrix that contains this part of the matrix:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix5.png"/>

In [ ]:
# exercise 1.6b, matrix slicing
data_slice = dataset[3:,2:]
data_slice


array([[21, 22, 23, 24],
       [27, 28, 29, 30],
       [33, 34, 35, 36]])

- Pick out this column slice from data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series1.png"/>

In [ ]:
# exercise 1.6c, matrix slicing
data_slice = dataset[:4, 3]
data_slice


array([ 4, 10, 16, 22])

- Pick out this row from the data

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/series2.png"/>

In [ ]:
# exercise 1.6d, matrix slicing
data_slice = dataset[2]
data_slice

array([13, 14, 15, 16, 17, 18])

- Pick out these three rows from data:

<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/matrix6.png"/>

In [ ]:
# exercise 1.6e, matrix slicing
data_slice = dataset[3:, :]
data_slice

array([[19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

<h3><b>7. Use this matrix:</b></h3>

<b>dataset_2 = np.arange(1, 50).reshape(7, 7)</b>

- Add 50 to all values in the array (use broadcasting)

- Get the sum of all values in the dataset

- Get sum of only odd numbers in the dataset

- Get the standard deviation of the values in the dataset

- Get the sum of all values by ROW in the dataset

- Get the sum of all values by COLUMN in the dataset (tip, use the axis –parameter)

<br>

- <b>Extra task:</b> Do the total sum, row sum and column sum exercises< <b>without</b> NumPy in Python!

<br><br>
<img src="http://srv.plab.fi/~tuomasv/data_analytics_2023_images/exercise_set_1/desktopcomputer.png"/>


<b><h3>Exercise 1.7</h3></b>

In [ ]:
# exercise 1.7, NumPy -operations on a matrix
dataset_2 = np.arange(1, 50).reshape(7, 7)
dataset_2

# use additional code cells or different variable names for each subtask


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [ ]:
data = dataset_2 + 50
data

array([[51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [ ]:
data_sum = np.sum(dataset_2)
data_sum

1225

In [ ]:
data_odds = np.sum(dataset_2[dataset_2 % 2 == 1])
data_odds

625

In [ ]:
dev = np.std(dataset_2)
dev

14.142135623730951

In [ ]:
data_rows = np.sum(dataset_2, axis=1)
data_rows

array([ 28,  77, 126, 175, 224, 273, 322])

In [ ]:
data_columns = np.sum(dataset_2, axis=0)
data_columns

array([154, 161, 168, 175, 182, 189, 196])